Name : Prashant Sanjay Sonar
    
Employee ID : AIS028

Task 2

Q1:What is an array?

Ans:
An array is a data structure that contains a group of elements and these elements are all of 
the same data type, such as an integer or string.
Arrays are commonly used in computer programs to organize data so that a related set of values
can be easily sorted or searched.

For example, if you want to store 100 integers, you can create an array for it. int data[100]

Q2 : What is difference between array and list?

Ans:
Array : Elements are stored in linear order but accecisable with an index

        Array have a fixed sized.
        
        Array can access previous elements easily
        
        Arrays are binary search.


List : Elements are stored in linear order but accecisable with Links.
       
       List do not have a fixed size
       
       List can't be access previous elements directly.
       
       List are no binary search.


Q3 : How to change the shape of an array?

Ans:
The reshape() function is used to give a new shape to an array without changing its data.
Array to be reshaped.


In [1]:
#For ex
 
import numpy as np
a=np.arange(1,7)
a
b=np.reshape(a,(2,3))
display(a,b)

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

Q4 : What does the name.strip () do?

Ans:
The strip() method returns a copy of the string by removing both the leading and the trailing 
characters (based on the string argument passed). The strip() method removes characters 
from both left and right based on the argument (a string specifying the set of characters to be removed).

In [2]:
# For ex. 
s='  n Artificial n  '
print(s.strip('n'))
print(s.strip('n '))
print(s.strip(' n'))



  n Artificial n  
Artificial
Artificial


Q5 : When we use triple single or triple double quotes to define a string?


Ans: """ With triple quotes, you can print strings on multiple lines to make text, especially lengthy text, easier to read. this case can be used.

# Coding Exercise:

In [3]:
#Q6 : Create a character type array?

#Ans: 
charar=np.chararray((3,3))
charar[:]='a'
charar

chararray([[b'a', b'a', b'a'],
           [b'a', b'a', b'a'],
           [b'a', b'a', b'a']], dtype='|S1')

In [4]:
#Q7 : Create a “hello” string and access the string character "ll" in python?

#Ans:
s1="Hello"
print(s1)
s1[2:4]

Hello


'll'

In [5]:
#Q8 :Create an array to get largest and smallest number using minimum and maximum function?

#Ans:
ar1=[34,2,5,6,76,89,123]
display(min(ar1),max(ar1))

2

123

In [6]:
#Q9:If name is “core python” then access the "python" from name and reverse "python" using slicing?

#Ans:
s1="core python"
s2=s1[5:12]
s2

'python'

In [7]:
s2='python'[::-1]
print(s2)

nohtyp


Q10 : Create an array of integer type and add element 12 using append method and remove one
element using remove methods?

In [8]:
#Ans:
#add element using append fun
arr1=[1,2,3,4,5,6]
np.append(arr1,12)


array([ 1,  2,  3,  4,  5,  6, 12])

In [9]:
#delete element using remove fun
arr1.remove(1)
print(arr1)

[2, 3, 4, 5, 6]


In [10]:
#Q11 : Create a single dimensional and 3 dimensional array using numpy?

#Ans:
array1=np.array([1,2,3,4,5])                  #single dimensional
array2=np.random.randint(1,10,(2,3,3))        #3 dimensional
display(array1,array2)
    

array([1, 2, 3, 4, 5])

array([[[1, 6, 7],
        [5, 9, 2],
        [4, 4, 7]],

       [[7, 5, 1],
        [1, 9, 3],
        [8, 9, 9]]])

In [11]:
#Q12 :Create a “Programiz” string and convert the string into upper, lower case? 
#     And replace given string by “program” using replace method?

#Ans:
a="Programiz"
a.upper()

'PROGRAMIZ'

In [12]:
a.lower()

'programiz'

In [13]:
#replace method
a.replace('Programiz','program')

'program'

In [14]:
# Q13 : Create a two array one using linspace and another using arange function and
        #then subtract array1 from array 2?

#Ans:
ar1=np.arange(11,20).reshape(3,3)
ar2=np.arange(1,10).reshape(3,3)
display(ar1,ar2)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar1-ar2   # np.subtract(ar1,ar2)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
# Q14 :Create a “happy new year” string and then separate this string by (space) ",”?

#Ans:
stri1="happy new year"
stri1.split(",")

['happy new year']

Q15 : Create two string and check whether one string present in another string using membership operator?

In [17]:
#Ans:
strr1='Hello'
strr2='Hello world'
print(strr1 in strr2)

True
